language: node_js

node_js:
  - "8"

cache:
    yarn: true
    directories:
        - node_modules

install:
    yarn install


script:
    git config --global user.email ${GIT_EMAIL}
    yarn run build
    yarn run deploy -r https://${GIT_TOKEN}@github.com/kamthamc/resume.git

branches:
    only:
        - master
        - develop
        - /^greenkeeper/.*$/
