language: node_js

node_js:
  - "8"

cache:
    yarn: true
    directories:
        - node_modules

install:
    yarn install


script:
    git config user.email ${GIT_EMAIL}
    yarn run deploy

branches:
    only:
        - master
        - develop
        - /^greenkeeper/.*$/
